# Формы для заполнения MongoDB
form_data = [
    dict(
        name="my_form",
        length_form=4,
        email="my_email",
        date="my_date",
        phone="my_phone",
        text="texted",
    ),
    dict(
        name="admin_form",
        length_form=4,
        email="admin_email",
        date="admin_date",
        phone="admin_phone",
        text="text",
    ),
    dict(
        name="director_form",
        length_form=4,
        email="my_email_director",
        date="date",
        phone="phones",
        text="text_custom",
    ),
    dict(
        name="banned_form",
        length_form=4,
        email="banned_email",
        date="date",
        phone="phone",
        text="text",
    ),
    dict(
        name="user_form",
        length_form=3,
        email="user_email",
        date="user_date",
        text="text_user",
    ),
    dict(
        name="winner_form",
        length_form=3,
        email="winner_email",
        date="date",
        phone="phone",
    ),
    dict(
        name="loser_form",
        length_form=3,
        email="loser_email",
        phone="loser_phone",
        text="text",
    ),
    dict(
        name="leader_form",
        length_form=3,
        email="leader_email",
        phone="leader_phone",
        text="text",
    ),
    dict(
        name="default_form_4_field",
        length_form=4,
        email="email",
        date="date",
        phone="phone",
        text="text",
    ),
    dict(
        name="default_form_3_field",
        length_form=3,
        email="email",
        date="date",
        text="text",
    ),
    dict(
        name="default_form_2_field",
        length_form=2,
        email="email",
        phone="phone"
    ),
    dict(
        name="default_form_1_field",
        length_form=1,
        email="email"
    ),
]
